- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download gcloud GPG key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/keyrings/gcloud.gpg
    mode: '0644'
    force: true

- name: Adds gcloud repos
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/gcloud.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    filename: packages_cloud_google_com_apt
    update_cache: false

- name: Installs google-cloud-sdk
  ansible.builtin.apt:
    pkg: google-cloud-sdk
    state: present
    update_cache: true
  when: not ansible_check_mode

- name: Installs google-cloud-sdk extras
  ansible.builtin.apt:
    pkg: "{{ gcloud_extras }}"
    state: present
  when: not ansible_check_mode