---

- name: "Force 'gcloud_key' to be set as string not as vault for next filters"
  set_fact:
    gcloud_key: "{{ gcloud_key }}"

- name: Create temporary file
  tempfile:
     state: file
     suffix: .json
  register: __gcloud_temp_key

- name: Copy temp file
  copy:
      content: '{{ gcloud_key }}'
      dest: '{{ __gcloud_temp_key.path }}'

- name: Activate service account
  shell: "CLOUDSDK_PYTHON_SITEPACKAGES=1 gcloud auth activate-service-account {{ gcloud_key | json_query('client_email') }} --key-file {{ __gcloud_temp_key.path }}"

- name: Sets default project
  command: gcloud config set core/project {{ gcloud_key | json_query('project_id') }}
  when: gcloud_set_as_default

- name: Remove gcloud servicekey
  file:
    path: "{{ __gcloud_temp_key.path }}"
    state: absent
